name: rethinkdb
version: 2.3.5
summary: The open-source database for the real-time web
description: |
  RethinkDB is the first open-source, scalable JSON database built from the
  ground up for the realtime web. It inverts the traditional database
  architecture by exposing an exciting new access model – instead of polling
  for changes, the developer can tell RethinkDB to continuously push updated
  query results to applications in realtime. RethinkDB’s realtime push
  architecture dramatically reduces the time and effort necessary to build
  scalable realtime apps.

  In addition to being designed from the ground up for realtime apps,
  RethinkDB offers a flexible query language, intuitive operations and
  monitoring APIs, and is easy to setup and learn.
confinement: strict

apps:
  launch:
    daemon: forking
    command: bin/launch.sh start
    stop-command: bin/launch.sh stop
    plugs: [ network-bind, log-observe ]
  rethinkdb:
    command: bin/rethinkdb
    plugs: [ network-bind, log-observe ]

parts:
  rethink-db:
    plugin: autotools
    source: https://download.rethinkdb.com/dist/rethinkdb-2.3.5.tgz
    configflags: [ ]
    build-packages: [
      build-essential, protobuf-compiler, python, libprotobuf-dev,
      libcurl4-openssl-dev, libboost-all-dev, libncurses5-dev,
      wget, m4]
    organize:
      usr/local/bin: bin
    filesets:
      binaries:
        - bin/*
      libraries:
        - usr/lib/*
    snap:
      - $binaries
      - $libraries
  launcher:
    plugin: dump
    source: .
    stage:
      - bin/launch.sh

